### ISSUE TITLE
原理大概是什么样的。

### ISSUE THREAD

**Issue by replive** [xjdrew/kone#1]
原理大概是什么样的,能大概讲下吗，没学过go.

**Comment by xjdrew** [comment]
原理跟go没关系，什么语言都可以实现。
简单说是通过dns欺骗把需要代理的流量重定向到虚拟网卡，虚拟网卡对流量重整后走代理出去。

**Comment by yesme2000** [comment]
那这个只能处理http请求了？

**Comment by lovedboy** [comment]
@yesme2000 TCP/UDP/ICMP 都可以

**Comment by Coneboy-k** [comment]
kone启动流程
0.读取config文件
1.监听82端口
2.开启dns服务监听53端口

client访问kone流程
1.查询DNS记录
  1.kone从table中读取nat地址，否则生成nat地址
2.client拿到dns给的IP进行访问
  1.判断table中是否存在nat地址，否则关闭链接 
  2.生成session，绑定src.ip src.port 和 outerIP port
  3.kone建立访问链接，此时判断是否需要进行代理。
  4.修改kone访问链接的checksum等信息。
  5.关联client-》kone和kone-》目的主机的数据流。
  6.完成后关闭双向链接。


注意:
1.TUN是工作在第三层。TAP工作在第二层。
2.kone采用的是DNAT，会根据目标IP进行生成。单也不是完全的DNAT。

没搞过go，硬着头皮看的，勿喷哈。
