### ISSUE TITLE
能否支持动态更新配置文件呢？或者把dns记录缓存到磁盘

### ISSUE THREAD

**Issue by miniers** [xjdrew/kone#13]
如果更新配置后重启，会造成上次的解析记录失效，需要手动刷新下dns缓存

**Comment by xjdrew** [comment]
解析出来的IP是跟域名的hash值相关的。如果ip空间够大，重启后大部分不会失效，偶尔出现hash值冲突才会失效。

**Comment by miniers** [comment]
get，谢谢解释😅
