### ISSUE TITLE
Kone will crash every 10 mins around

### ISSUE THREAD

**Issue by tangye1234** [xjdrew/kone#15]
I use kone script in my company within 300 stuffs.
Now when I set kone as the dns server, it will crash at interval of 10 mins.
So how can I help to find the reason? May be I can fetch some logs.

**Comment by tangye1234** [comment]
loge shows：
11:20:59 gfw.vmovier.cc kone[15946]: 17-08-01 11:20:59.945 ERRO @main.go:50 one quit: accept tcp4 10.192.0.1:82: accept4: too many open files

**Comment by FlowerWrong** [comment]
改下系统设置应该可以，很多go程序都有这个问题，原因不明。

**Comment by tangye1234** [comment]
ulimit -n 51200
echo 51200 > /proc/sys/fs/file-max

It still fails with too many open files error, while the difference is the working-time will last longer

**Comment by xjdrew** [comment]
I'll make it just print some errors, not quit.
