### ISSUE TITLE
;; Got recursion not available from

### ISSUE THREAD

**Issue by tangye1234** [xjdrew/kone#16]
已经假设kone好几天了

不过如果dns，一个使用kone，一个使用别的，nslookup不一会就会出现这个错误：
;; Got recursion not available from [kone dns server]

然后就使用另一个dns了。
这个是什么原因呢，我现在只好架设了两个kone server。

**Comment by xjdrew** [comment]
客户端配置两个dns地址，一个是别的dns，一个是kone？

你搜索一下这个错误，我没遇到过。

**Comment by tangye1234** [comment]
➜  ~ dig www.google.com.hk

; <<>> DiG 9.8.3-P1 <<>> www.google.com.hk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28454
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;www.google.com.hk.  IN A

;; ANSWER SECTION:
www.google.com.hk. 600 IN A 10.172.66.203

;; Query time: 3 msec
;; SERVER: 192.168.9.10#53(192.168.9.10)
;; WHEN: Wed Aug  9 18:06:50 2017
;; MSG SIZE  rcvd: 68

如果dig一个kone dns server，就会出现这个Warnning: **;; WARNING: recursion requested but not available**

这个时候，你有两个nameserver，nslookup就会跳过这个dns，使用下一个。

**Comment by tangye1234** [comment]
#18 can fix this issue. can we make this an opt-in configuration?

**Comment by xjdrew** [comment]
#18 fix it!
