### ISSUE TITLE
对于Telegram这种会检查ip污染的应用来说怎么办

### ISSUE THREAD

**Issue by tangye1234** [xjdrew/kone#17]
我发现，部分应用会检查ip污染情况，这类需要翻墙的应用使用kone，就无法得到处理。

各位有什么好的办法解决这个问题吗？

**Comment by FlowerWrong** [comment]
See [example.ini](https://github.com/xjdrew/kone/blob/master/example.ini#L41), work with `route`.

**Comment by tangye1234** [comment]
@FlowerWrong 能否解释一下其中的东西。route那里的设置，不太明白。还请指导一下。

**Comment by tangye1234** [comment]
@FlowerWrong 能否解释一下其中的东西。route那里的设置，不太明白。还请指导一下。你的意思是把要参与翻墙的ip，加入到route即可对吗？

**Comment by xjdrew** [comment]
@tangye1234

 telegram直接使用ip连接，没使用域名，所以不能通过劫持域名的方式来重定向。

需要通过重定向ip来实现。
先在通过[route]设置telegram的ip段，kone启动后会自动设置操作系统路由表，把那些ip段的流量出口设置为kone创建的虚拟网卡，使kone可以接管这些流量。
后面就跟接管了域名一样：加一条规则，给这些ip指定一个代理出口（必须指定一个代理出口，否则会死循环）。
