### ISSUE TITLE
请求无限循环

### ISSUE THREAD

**Issue by Fndroid** [xjdrew/kone#26]
你好，向您请教一个问题。

假设在config.ini中配置了对应的规则后，如果判断为通过代理连接，但是代理服务器（本地代理）中分流时判断为直连，此时连接是否会无限循环？

**Comment by Coneboy-k** [comment]
我这边代理使用clash . kone的作用是一个dns 和 转发请求到clash的作用。

**Comment by xjdrew** [comment]
之前规则配置循环，可能会无限循环。这次规则优化后，增加了保护，应该很难配置出这种情况。https://github.com/xjdrew/kone/blob/bbe0a47fe8406c553fd9ffb49ec2853ac0d2f866/tcp_relay.go#L88
