### ISSUE TITLE
Should we support windows 7 ?

### ISSUE THREAD

**Issue by SUCHMOKUO** [xjdrew/kone#27]
Hi !

I forked this repo, and then I tried to make it support windows, now it works on windows 10.

However, due to using PowerShell's NETTCPIP module to set route table and some other stuff, it's not possible to work under windows 8. But I think there are still many windows 7 users, and it's possible to do the same thing with NETSH instead of PowerShell, so what's your opinion about support windows 7 or not?

By the way, could I open a pull request to help this project support windows ?

Thanks !

**Comment by xjdrew** [comment]
Have merged your PR，thanks!
